FROM lukemathwalker/cargo-chef:latest-rust-1.67 as chef

WORKDIR /app

RUN apt update && apt install lld clang -y

RUN rustup install nightly

# -----------------------------

FROM chef AS planner

COPY . .

RUN cargo +nightly chef prepare --recipe-path recipe.json

# -----------------------------

FROM chef AS builder

COPY --from=planner /app/recipe.json recipe.json

RUN cargo +nightly chef cook --release --recipe-path recipe.json

COPY . . 


ENV SQLX_OFFLINE true

RUN cargo +nightly build --release --bin audius_network_monitor

# ----------------------------

FROM debian:bullseye-slim AS runtime

WORKDIR /app

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl ca-certificates \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/audius_network_monitor audius_network_monitor

COPY migrations migrations
COPY configuration configuration
ENV APP_ENVIRONMENT stage

ENTRYPOINT ["./audius_network_monitor"]