version: '3'
services:
  network-monitoring-db:
    image: postgres:14
    shm_size: 4gb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trust
      POSTGRES_DB: audius_network_monitoring
    volumes:
      - postgres_data_network_monitoring_rs:/var/lib/postgresql/data/
    ports:
      - '5444:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  network-monitoring-push-gateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
  
  network-monitoring:
    build: 
      context: '.'
      dockerfile: Dockerfile.test
    depends_on:
      - network-monitoring-db
      - network-monitoring-push-gateway

volumes:
  postgres_data_network_monitoring_rs: