database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password" 
  database_name: "audius_network_monitoring"
foreign_database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password" 
  database_name: "audius_network_monitoring"
